docs: clarify supported distros for manager
osism/osism.github.io pull request #140
Opened 2023-11-14 13:54 UTC by artificial-intelligence

2023-11-14 13:54 UTC, artificial-intelligence commented
part of: https://github.com/osism/testbed/issues/1834

2023-11-17 17:32 UTC, berendt requested changes

2023-11-17 17:32 UTC, berendt commented on docs/advanced-guides/testbed.md
> +* currently only Ubuntu 22.04 is supported for the manager base distribution, this is caught by a precheck
This is confusing at this point as it is about the necessary tools on the workstation. On the workstation, it doesn't matter which operating system it is.

2023-11-17 17:32 UTC, berendt commented on docs/advanced-guides/testbed.md
> +* currently only Ubuntu 22.04 is supported for the manager base distribution, this is caught by a precheck
It makes sense to mention this in the description of the variable `image`.

2024-02-14 13:10 UTC, closed without merging