Add simple configuration guides for all supported OpenStack services
osism/osism.github.io pull request #398
Opened 2024-03-27 15:07 UTC by janhorstmann

Part of https://github.com/osism/issues/issues/938

2024-03-27 15:11 UTC, janhorstmann commented
I have taken the list of supported services from the [release respository version 7.0.0](https://github.com/osism/release/blob/main/7.0.0/openstack-2023.2.yml#L37)

Do you want to keep the links currently used in the `nova` docs or want it to be more uniform?

The `skyline-apiserver` project seems not to have an admin guide, so I have not added a link

2024-03-27 15:42 UTC, berendt commented
Use a single skyline file and add console & api server there.

Add additional neutron services (dynamic routing, vpnaas) to the neutron file and not in separate files.

2024-03-27 15:43 UTC, berendt commented
Always add a link (if it exists) to the configuration reference (like https://docs.openstack.org/nova/latest/configuration/config.html) as well.

2024-03-27 15:45 UTC, berendt commented
For some services the configuration guide is the same like the configuration reference. In this case only add a single link and name it configuration reference.

The configuration reference is the page of all usable configuration parameters.

The configuration guide explains how to configure specific features.

2024-03-27 18:15 UTC, berendt requested changes
As commented before.

2024-03-28 13:48 UTC, janhorstmann commented
> For some services the configuration guide is the same like the configuration reference. In this case only add a single link and name it configuration reference.
> 
> The configuration reference is the page of all usable configuration parameters.
> 
> The configuration guide explains how to configure specific features.

Some services have sites titled "configuration **guide**", which only link to the configuration reference of one or more applications. Ich have included those as "configuration reference"  now, because they do not provide any further guidance, but the mismatch might be irritating for some.

2024-04-02 10:44 UTC, berendt commented on docs/guides/configuration-guide/openstack/octavia.md
> +
Also add https://docs.openstack.org/octavia/latest/configuration/configref.html as Octavia configuration guide.

2024-04-02 10:49 UTC, berendt commented on docs/guides/configuration-guide/openstack/manila.md
> +
Also add https://docs.openstack.org/manila/latest/configuration/shared-file-systems/samples/manila.conf.html as Manila configuration reference.

2024-04-02 17:12 UTC, merged