feat: add guide docs for rookify
osism/osism.github.io pull request #688
Opened 2024-09-25 12:34 UTC by boekhorstb1

adding docs for rookify

2024-10-07 09:23 UTC, b1-lender requested changes
Some smaller wording/grammar issues.

2024-10-08 07:37 UTC, boekhorstb1 commented on docs/guides/operations-guide/rookify.md
> +Make sure you can reach Rookifies code on you system. Then you can either:
Thanks! It should be Rookify's then though, will amend that. Using without apostrophe is also plural

2024-10-08 07:42 UTC, boekhorstb1 commented on docs/guides/operations-guide/rookify.md
> +    Currenlty rookify executes per default
I will have to adapt this, because we have just changed that. It runs `dry-run` per default now.

2024-10-08 08:54 UTC, boekhorstb1 commented on docs/guides/deploy-guide/rookify.md
> +## Install and Run from within a Container
thanks! Did that. Also added some gnu make and direnv as optional prerequisites

2024-10-08 09:02 UTC, b1-lender approved these changes

2024-10-31 13:02 UTC, NotTheEvilOne requested changes

2024-10-31 13:02 UTC, NotTheEvilOne commented on docs/guides/troubleshooting-guide/rookify.md
> +Nevertheless, it is **strongly advised** to test Rookify in a controlled environment first, such as the [OSISM testbed](https://github.com/osism/testbed). Additionally, ensure that precautionary back
nit: Additionally ensure that ... are made and all ...

2024-11-11 09:47 UTC, boekhorstb1 commented on docs/guides/operations-guide/rookify.md
> +### --help
thanks! :) I added `--migrate`

2024-11-11 09:52 UTC, boekhorstb1 commented on docs/guides/deploy-guide/rookify.md
> +- Kubernetes nodes must be deployed on at least the OSD nodes.
So, I  think you want me to add that line to the list of `Prerequisites & Requirements` right? Will do that :)

2024-11-13 20:19 UTC, NotTheEvilOne approved these changes
One last change I guess but otherwise than that it looks good for me as well :)

2024-11-13 20:19 UTC, NotTheEvilOne commented on docs/guides/operations-guide/rookify.md
> +Rookify's `execution-mode` allows you to run the migration. This a point of no (easy) return. Be sure to check all your configurations. Run `--migrate` or `-m` to execute the migration process.
nit: ... This is a point of no (easy) return ...

2024-11-14 08:23 UTC, boekhorstb1 commented
ok @berendt , all approved you can take another look if you like

2024-11-29 16:46 UTC, merged